### PR TITLE
Legion updates

### PR DESCRIPTION
**Pull request by ChronosSF**
Merged the updates from https://github.com/Paojy/Altz-UI/tree/master/Interface/AddOns/Aurora
Changed the default font in the Titles pane to Aurora's one.

Tested and working fine with the frames that were throwing errors / were not styled.

### CODE REVIEW

**Comment by Gethe** [comment]
Another PR was made and already merged in which had some overlap with yours. Please rebase this PR to the latest commit.

**Comment by ChronosSF** [comment]
I'll have to compare it thoroughly, though I think I merged a more recent commit since yours still contain beta-specific code which is not needed after the pre-patch.

C.isBetaClient = C.TOC >= 70000

Which is then used to switch between setTexture and setColorTexture, among other things.

**Comment by Gethe** [comment]
That PR was made prior to the patch going live, and I wanted it to work in both clients. That said, it is a fairly minor detail that doesn't really impact anything going forward.

**Comment by ChronosSF** [comment]
The PR should be good now. From what I can tell the changes from master are the following:
- Character pane stats separators are skinned
- The new loot pane is skinned
- Titles pane is skinned (just the font of the titles)
- Somewhat different TradeSkill window - I applied my change to the Learned/Unlearned tabs since they look better in my fork. The rest is from master. 

(by the way I think the expand/collapse buttons shouldn't get skinned in the TradeSkill window unless you can hook on their state change to hide the + button graphic. Right now it will always show a + regardless of their expand state).

**Comment by Gethe** [comment]
Looks pretty good so far, but a few notes:
 * The AchievementFrameHeaderLeftDDLInset is already hidden on line 19
 * Is there any particular reason parts of the AuctionProgressBar or SpellBook skin were removed? These are still needed.
 * The icons in the Legendaries browser have white corners. I would replace your usage of CreateBG with ReskinIcon

**Comment by ChronosSF** [comment]
Thanks for the comments. Restored the missing code - it looked like an erroneous removal.

Couldn't reproduce the white corners on the icons in the Legendaries browser but changed to ReskinIcon regardless (could be because I am using a custom icon set?). Hope it's good now.

**Comment by Gethe** [comment]
Ah yeah, if you're using a custom icon set (clean Icons?) then you wouldn't see it.

**Comment by ChronosSF** [comment]
Clean Icons, yes. I'll remove them to test with ReskinIcon (unless you were already able to).

**Pull request merged**
