### PR TITLE
Classic compatibility

### PR DESCRIPTION
**Pull request by MisatoTremor**
### What does this implement/fix? Explain your changes ###

Fixes WoW Classic compatibility. This is based on tag 8.1.0.4 (Commit f05d5f72511e20450431f36a4ea3543e5dafb7d3) as Classic is based on WoW 8.1.0, so I suggest to create a branch from that commit and then set the base branch of this PR to it.

### Does this close any currently open issues? ###

#172 

### Any relevant logs, error output, etc? ###

None

### Any other comments? ###

Some elements are not yet skinned (reintroduced old UI), but works with classic

### CODE REVIEW

**Comment by Gethe** [comment]
What changes do you keep force pushing? If your going to make additional changes to a PR, keep those changes as separate commits.

**Comment by MisatoTremor** [comment]
Sorry, I'm just so used to squashing all commits for PRs from other projects, that I did it automatcally. But will keep that in mind when pushing further updates here.

**Comment by Gethe** [comment]
Really? Is that common?

Also, while I appreciate the work you've done here, I'm going to be using the changes on my own branch.

**Comment by MisatoTremor** [comment]
Uhh. I can't say how common that really is, just common in the ecosystem I usually contribute in. And of course nothing is wrong with your approach. It definately has the plus of better reproducibility of the development of a PR.

Hopefully you can use bits of my work, but I wanted to do it anyway as part of my classic implementation for RealUI and it was good for learning some of LUAs fallacies. 😄

**Pull request closed without merging**
